### ISSUE TITLE
How to ensure that at a time only one group should be expanded rest all should be in collapsed state?

### ISSUE THREAD

**Issue by krishnameena** [jeantimex/ios-swift-collapsible-table-section#20]

**Comment by jeantimex** [comment]
There are two solutions:

1. Keep track of the index of the last expanded section, in the `toggleSection` function, mark the current expanded section to collapsed and the selected section to expanded.

2. In the `toggleSection` function, mark all the sections as collapsed except the selected one, and then reload all the rows.

Hope that makes sense.

**Comment by krishnameena** [comment]
I have done it using point 2.

I earlier also thought about it but facing issue in header arrow as it was not updating so I fixed it using this

`myTableView.reloadSections(IndexSet(integersIn: 0...sections.count-1), with: .automatic)`

**Comment by jeantimex** [comment]
Nicely done, just curious, I thought reloadSections() will redraw the whole section including the section header, and it will break any animation in the header, for example, you won't be able to see the rotation of the arrow, that's why I only reload the rows not the sections. Correct me if I am wrong.

**Comment by krishnameena** [comment]
Yes you are right but what else I can do so that it should work fine.

**Comment by anupamchugh** [comment]
Instead of reloading all the sections like you did above, just reload the two sections - current and previously opened one.
